spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      fail-fast: false # true in prod

server:
  tomcat:
    threads:
      max: 50
      min-spare: 5
    connection-timeout: 2s
    keep-alive-timeout: 15s

  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: Test Greeting